from src.controller.aluguel_controller import AluguelController
from src.controller.brinquedo_controller import BrinquedoController
from src.controller.cliente_controller import ClienteController
from src.controller.equipe_controller import EquipeController
from src.controller.pessoa_controller import PessoaController
from src.controller.pessoa_equipe_controller import PessoaEquipeController
